In [41]:
import pandas as pd
import numpy as np

### Read Excel file .. parse the sheets (tables) in it

In [34]:
## this gives you an Excel file object
excel = pd.ExcelFile('/Users/csstnns/Desktop/Python Data Course - Oct2020/Day 2/UCL-updated.xlsx')

In [35]:
## once you have it .. you can list the sheets in there
excel.sheet_names

['Sheet3', 'NewSheet3']

In [4]:
data = excel.parse('ThirdSheet')

In [8]:
data['Squared-Y1-area'] = data['Y1-area'] ** 2

In [9]:
data

,Unnamed: 0,B-area,B-volume,Y1-count,Y1-area,Y1-volume,Y2-count,Y2-area,Y2-volume,CubedY2-area,Squared-Y1-area
0,0,0.00,0.000,0,0.00,0.000,0,0.00,0.000,0.000000,0.0000
1,1,0.00,0.000,0,0.00,0.000,2,0.10,0.003,0.001000,0.0000
2,2,0.00,0.000,1,0.01,0.000,2,0.19,0.005,0.006859,0.0001
3,3,0.00,0.000,0,0.00,0.000,0,0.00,0.000,0.000000,0.0000
4,4,0.00,0.000,1,0.01,0.000,1,0.01,0.003,0.000001,0.0001
5,5,0.00,0.000,3,0.18,0.005,3,0.24,0.006,0.013824,0.0324
6,6,0.00,0.000,0,0.00,0.000,3,0.38,0.015,0.054872,0.0000
7,7,0.00,0.000,2,0.02,0.001,0,0.00,0.000,0.000000,0.0004
8,8,0.00,0.000,0,0.00,0.000,0,0.00,0.000,0.000000,0.0000
9,9,0.00,0.000,1,0.03,0.001,1,0.06,0.002,0.000216,0.0009
10,10,0.00,0.000,0,0.00,0.000,0,0.00,0.000,0.000000,0.0000
11,11,0.00,0.000,0,0.00,0.000,1,0.99,0.036,0.970299,0.0000
12,12,0.00,0.000,3,0.08,0.003,0,0.00,0.000,0.000000,0.0064
13,13,0.00,0.000,1,0.04,0.001,1,0.08,0.002,0.000512,0.0016
14,14,0.00,0.000,0,0.00,0.000,0,0.00,0.000,0.000000,0.0000
15,15,0.00,0.000,4,0.21,0.007,2,0.13,0.004,0.002197,0.0441
16,16,0.00,0.000,0,0.00,0.000,0,0.00,0.000,0.000000,0.0000
17,17,0.00,0.000,1,0.05,0.001,1,0.03,0.001,0.000027,0.0025
18,18,0.00,0.000,0,0.00,0.000,0,0.00,0.000,0.000000,0.0000
19,19,0.00,0.000,0,0.00,0.000,0,0.00,0.000,0.000000,0.0000
20,20,0.00,0.000,0,0.00,0.000,2,0.08,0.002,0.000512,0.0000
21,21,0.00,0.000,0,0.00,0.000,0,0.00,0.000,0.000000,0.0000
22,22,0.00,0.000,0,0.00,0.000,0,0.00,0.000,0.000000,0.0000
23,23,0.00,0.000,7,0.26,0.007,5,0.50,0.013,0.125000,0.0676
24,24,0.00,0.000,1,0.02,0.001,5,0.32,0.008,0.032768,0.0004
25,25,0.02,0.000,1,0.02,0.000,2,0.11,0.003,0.001331,0.0004
26,26,0.00,0.000,0,0.00,0.000,0,0.00,0.000,0.000000,0.0000
27,27,0.00,0.000,0,0.00,0.000,0,0.00,0.000,0.000000,0.0000
28,28,0.02,0.000,1,0.03,0.001,1,0.02,0.001,0.000008,0.0009
29,29,0.00,0.000,0,0.00,0.000,0,0.00,0.000,0.000000,0.0000
30,30,0.10,0.003,2,0.21,0.005,3,0.43,0.011,0.079507,0.0441

In [12]:
data.drop('Y1-count', axis=1, inplace = True)

In [13]:
data.columns

Index(['Unnamed: 0', 'B-area', 'B-volume', 'Y1-area', 'Y1-volume', 'Y2-count',
       'Y2-area', 'Y2-volume', 'CubedY2-area', 'Squared-Y1-area'],
      dtype='object')

## Attach dataframe as a new sheet to an existing Excel file (Append)

In [31]:
excel_writer = pd.ExcelWriter('/Users/csstnns/Desktop/Python Data Course - Oct2020/Day 2/UCL-updated.xlsx'
                             ,engine="openpyxl", mode = 'a')

In [36]:
## try an existing sheet name to overwrite that sheet
data.to_excel(excel_writer, sheet_name='NewSheet3')

In [37]:
excel_writer.close()

## Attach dataframe as a new sheet to a new Excel file

In [39]:
## Make sure you use a non-existing file name under that path
excel_writer = pd.ExcelWriter('/Users/csstnns/Desktop/Python Data Course - Oct2020/Day 2/UCL-updated_new.xlsx')

In [42]:
## just to make things more inyteresting .. add new sheets
country_info = pd.read_csv('/Users/csstnns/Desktop/Python Data Course - Oct2020/Day 2/country_info.csv')
## create a pivot table
my_pivot_table = pd.pivot_table(country_info, index=['continent','country'], 
               values=['lifeExp','pop','gdpPercap'],
                                aggfunc=[np.std,np.median,'mean'])

In [43]:
data.to_excel(excel_writer, sheet_name='Sheet3')
my_pivot_table.to_excel(excel_writer, sheet_name='CountryPivotTable')


excel_writer.close()

In [44]:
data

,Unnamed: 0,B-area,B-volume,Y1-area,Y1-volume,Y2-count,Y2-area,Y2-volume,CubedY2-area,Squared-Y1-area
0,0,0.00,0.000,0.00,0.000,0,0.00,0.000,0.000000,0.0000
1,1,0.00,0.000,0.00,0.000,2,0.10,0.003,0.001000,0.0000
2,2,0.00,0.000,0.01,0.000,2,0.19,0.005,0.006859,0.0001
3,3,0.00,0.000,0.00,0.000,0,0.00,0.000,0.000000,0.0000
4,4,0.00,0.000,0.01,0.000,1,0.01,0.003,0.000001,0.0001
5,5,0.00,0.000,0.18,0.005,3,0.24,0.006,0.013824,0.0324
6,6,0.00,0.000,0.00,0.000,3,0.38,0.015,0.054872,0.0000
7,7,0.00,0.000,0.02,0.001,0,0.00,0.000,0.000000,0.0004
8,8,0.00,0.000,0.00,0.000,0,0.00,0.000,0.000000,0.0000
9,9,0.00,0.000,0.03,0.001,1,0.06,0.002,0.000216,0.0009
10,10,0.00,0.000,0.00,0.000,0,0.00,0.000,0.000000,0.0000
11,11,0.00,0.000,0.00,0.000,1,0.99,0.036,0.970299,0.0000
12,12,0.00,0.000,0.08,0.003,0,0.00,0.000,0.000000,0.0064
13,13,0.00,0.000,0.04,0.001,1,0.08,0.002,0.000512,0.0016
14,14,0.00,0.000,0.00,0.000,0,0.00,0.000,0.000000,0.0000
15,15,0.00,0.000,0.21,0.007,2,0.13,0.004,0.002197,0.0441
16,16,0.00,0.000,0.00,0.000,0,0.00,0.000,0.000000,0.0000
17,17,0.00,0.000,0.05,0.001,1,0.03,0.001,0.000027,0.0025
18,18,0.00,0.000,0.00,0.000,0,0.00,0.000,0.000000,0.0000
19,19,0.00,0.000,0.00,0.000,0,0.00,0.000,0.000000,0.0000
20,20,0.00,0.000,0.00,0.000,2,0.08,0.002,0.000512,0.0000
21,21,0.00,0.000,0.00,0.000,0,0.00,0.000,0.000000,0.0000
22,22,0.00,0.000,0.00,0.000,0,0.00,0.000,0.000000,0.0000
23,23,0.00,0.000,0.26,0.007,5,0.50,0.013,0.125000,0.0676
24,24,0.00,0.000,0.02,0.001,5,0.32,0.008,0.032768,0.0004
25,25,0.02,0.000,0.02,0.000,2,0.11,0.003,0.001331,0.0004
26,26,0.00,0.000,0.00,0.000,0,0.00,0.000,0.000000,0.0000
27,27,0.00,0.000,0.00,0.000,0,0.00,0.000,0.000000,0.0000
28,28,0.02,0.000,0.03,0.001,1,0.02,0.001,0.000008,0.0009
29,29,0.00,0.000,0.00,0.000,0,0.00,0.000,0.000000,0.0000
30,30,0.10,0.003,0.21,0.005,3,0.43,0.011,0.079507,0.0441

In [46]:
for value in data['Y1-volume']:
    print(value)

0.0
0.0
0.0
0.0
0.0
0.005
0.0
0.001
0.0
0.001
0.0
0.0
0.003
0.001
0.0
0.007
0.0
0.001
0.0
0.0
0.0
0.0
0.0
0.007
0.001
0.0
0.0
0.0
0.001
0.0
0.005